name: Selenium Test Workflow

on: push

jobs:
  Selenium_Test_Job1:
    name: Selenium Test Job
    runs-on: windows-latest
    env: 
      SELENIUM_DRIVER: 'RemoteWebDrivers'
    
    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in GitHub"
      - name: Check out source code
        uses: actions/checkout@v2.4.0
      - run: echo "This repo is ${{ github.repository }} .."
      - name: Run a inline script
        run: |
          mkdir newfolder
          ls -l
        shell: bash
      - name: Run a script file from repo
        if: ${{ always() }}
        run: sh ./run.sh
        shell: pwsh
      - name: Execute during failure
        if: ${{ failure() }}
        run: echo "One of the step seems failed"
      - name: Run Selenium Test
        if: ${{ env.SELENIUM_DRIVER == 'RemoteWebDriver' }}
        run: echo "Running test in Selenium grid setup"
        
        
  Selenium_test_Job2:
    name: Selenium Test Job 2
    runs-on: ubuntu-latest
    needs: Selenium_Test_Job1
    if: ${{ always() }}
    
    steps:
      - run: echo "This is from second job"
    
         
      
